export { DID } from './DID/DID';
export { DIDDocument } from './DID/DIDDocument';
export { Service, ServiceDataModel } from './DID/Service';
export { BaseKeypair } from './Encryption/BaseKeypair';
export { Hash } from './Encryption/Hash';
export { CreateRandomDID, CreateRandomDIDFromPublicKey } from './Helpers/CreateRandomDID';
export { DecodeProofDocument } from './Helpers/DecodeProofDocument';
export { SignDIDAuthentication, VerifyDIDAuthentication } from './Helpers/DIDAuthentication';
export { GenerateRSAKeypair, GenerateECDSAKeypair } from './Helpers/GenerateKeypair';
export { GenerateSeed } from './Helpers/GenerateSeed';
export { DIDPublisher } from './IOTA/DIDPublisher';
export { MAMSettings } from './IOTA/mam';
export { Proof, ExtendedProofDocument, ProofBuildingMethod, SigningMethod, VerifySignatureMethod, ProofParameters } from './VC/Proof/Proof';
export { ProofTypeManager } from './VC/Proof/ProofTypeManager';
export { Credential, CredentialDataModel } from './VC/Credential';
export { Presentation, PresentationDataModel } from './VC/Presentation';
export { Schema } from './VC/Schema';
export { SchemaManager } from './VC/SchemaManager';
export { VerifiableCredential, VerifiableCredentialDataModel } from './VC/VerifiableCredential';
export { VerifiablePresentation, VerifiablePresentationDataModel } from './VC/VerifiablePresentation';
